// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR0l-K640xeaEmyzojwbwn1J-44OcPJcU',
    appId: '1:896706123947:web:69784da80b19701d21ffee',
    messagingSenderId: '896706123947',
    projectId: 'datosproyectomindcare',
    authDomain: 'datosproyectomindcare.firebaseapp.com',
    storageBucket: 'datosproyectomindcare.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzMwDMBoswYoNcHzGkP5S4HBSHN3H6MT4',
    appId: '1:896706123947:android:51fbaf9bcb6a199221ffee',
    messagingSenderId: '896706123947',
    projectId: 'datosproyectomindcare',
    storageBucket: 'datosproyectomindcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPK5Jd3ikqlwQynsfo-8dQWjz6emYVUhI',
    appId: '1:896706123947:ios:a6a37e826e71015821ffee',
    messagingSenderId: '896706123947',
    projectId: 'datosproyectomindcare',
    storageBucket: 'datosproyectomindcare.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPK5Jd3ikqlwQynsfo-8dQWjz6emYVUhI',
    appId: '1:896706123947:ios:a6a37e826e71015821ffee',
    messagingSenderId: '896706123947',
    projectId: 'datosproyectomindcare',
    storageBucket: 'datosproyectomindcare.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
